package com.commonrail.mtf.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.commonrail.mtf.db.Files;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FILES".
*/
public class FilesDao extends AbstractDao<Files, Void> {

    public static final String TABLENAME = "FILES";

    /**
     * Properties of entity Files.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property FileType = new Property(0, String.class, "fileType", false, "FILE_TYPE");
        public final static Property FileUrl = new Property(1, String.class, "fileUrl", false, "FILE_URL");
        public final static Property FileLocalUrl = new Property(2, String.class, "fileLocalUrl", false, "FILE_LOCAL_URL");
        public final static Property FileLen = new Property(3, String.class, "fileLen", false, "FILE_LEN");
        public final static Property FileStatus = new Property(4, int.class, "fileStatus", false, "FILE_STATUS");
    };


    public FilesDao(DaoConfig config) {
        super(config);
    }
    
    public FilesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FILES\" (" + //
                "\"FILE_TYPE\" TEXT NOT NULL ," + // 0: fileType
                "\"FILE_URL\" TEXT NOT NULL UNIQUE ," + // 1: fileUrl
                "\"FILE_LOCAL_URL\" TEXT NOT NULL ," + // 2: fileLocalUrl
                "\"FILE_LEN\" TEXT NOT NULL ," + // 3: fileLen
                "\"FILE_STATUS\" INTEGER NOT NULL );"); // 4: fileStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FILES\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Files entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getFileType());
        stmt.bindString(2, entity.getFileUrl());
        stmt.bindString(3, entity.getFileLocalUrl());
        stmt.bindString(4, entity.getFileLen());
        stmt.bindLong(5, entity.getFileStatus());
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public Files readEntity(Cursor cursor, int offset) {
        Files entity = new Files( //
            cursor.getString(offset + 0), // fileType
            cursor.getString(offset + 1), // fileUrl
            cursor.getString(offset + 2), // fileLocalUrl
            cursor.getString(offset + 3), // fileLen
            cursor.getInt(offset + 4) // fileStatus
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Files entity, int offset) {
        entity.setFileType(cursor.getString(offset + 0));
        entity.setFileUrl(cursor.getString(offset + 1));
        entity.setFileLocalUrl(cursor.getString(offset + 2));
        entity.setFileLen(cursor.getString(offset + 3));
        entity.setFileStatus(cursor.getInt(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(Files entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(Files entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
