package com.commonrail.mtf.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INJECTOR_DB".
 */
public class InjectorDb {

    private String injectorType;
    private Integer orderNum;
    private String injectorName;
    private String iconUrl;

    public InjectorDb() {
    }

    public InjectorDb(String injectorType, Integer orderNum, String injectorName, String iconUrl) {
        this.injectorType = injectorType;
        this.orderNum = orderNum;
        this.injectorName = injectorName;
        this.iconUrl = iconUrl;
    }

    public String getInjectorType() {
        return injectorType;
    }

    public void setInjectorType(String injectorType) {
        this.injectorType = injectorType;
    }

    public Integer getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    public String getInjectorName() {
        return injectorName;
    }

    public void setInjectorName(String injectorName) {
        this.injectorName = injectorName;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

}
