package com.commonrail.mtf.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INJECTOR_DB".
 */
public class InjectorDb {

    /** Not-null value. */
    private String injectorType;
    private int orderNum;
    /** Not-null value. */
    private String injectorName;
    /** Not-null value. */
    private String iconUrl;

    public InjectorDb() {
    }

    public InjectorDb(String injectorType, int orderNum, String injectorName, String iconUrl) {
        this.injectorType = injectorType;
        this.orderNum = orderNum;
        this.injectorName = injectorName;
        this.iconUrl = iconUrl;
    }

    /** Not-null value. */
    public String getInjectorType() {
        return injectorType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInjectorType(String injectorType) {
        this.injectorType = injectorType;
    }

    public int getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(int orderNum) {
        this.orderNum = orderNum;
    }

    /** Not-null value. */
    public String getInjectorName() {
        return injectorName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInjectorName(String injectorName) {
        this.injectorName = injectorName;
    }

    /** Not-null value. */
    public String getIconUrl() {
        return iconUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

}
